# Generated by Django 3.2.9 on 2021-11-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('READING', 'Reading'), ('TAMPER', 'Tamper')], max_length=30)),
                ('reading', models.FloatField()),
                ('voltage', models.FloatField()),
                ('seq_number', models.PositiveIntegerField(unique=True)),
                ('recorded_on', models.DateTimeField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.device')),
            ],
        ),
    ]
