# Generated by Django 3.2.9 on 2021-11-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicereading',
            old_name='voltage',
            new_name='device_voltage',
        ),
    ]
